export const headers: any = {
    arcencohogarqa: {
      appKey: 'vtexappkey-arcencohogarqa-ZISRHH',
      appToken: 'EDTACZHVHDVJACOZNBEGHIBHRKFHBQKOFVKQBOQVMXFYUEKXBZBUDPIWBLJSTATQSHDFSXXYLITJCDMMZIFBPPKQNNPQFXBMEOFMAFEECCJUVYUYYWSLURBDWNRFIHTN',
    },
    arcencohogareasy: {
      appKey: 'vtexappkey-arcencohogar-ALVTUC',
      appToken: 'KQOOLSLDMQAJVLJBVQBSSICXGEVDGWELUKTQBDWPCQYFBRNCXFYPPHFBNQHHXHWQMPOLRTASUMQBKXVPQTFAXPWNFSCKVORUUHTLDBKEFGVDRDRQVSQECWTWTBGZQPWF',
    }
  }