query($collectionId: ID!, $page: Int!, $pageSize: Int!, $term: String = "") {
  products(
    collectionId: $collectionId
    page: $page
    pageSize: $pageSize
    term: $term
    filters: { collectionSkuId: $collectionId }
  ) @context(provider: "vtex.products-graphql") {
    items {
      id
      name
      imageUrl
      ref
      detailUrl
    }
    paging {
      page
      perPage
      total
      pages
    }
  }
}
